### ISSUE TITLE
Can VXLAN be used in the sloop.conf

### ISSUE THREAD

**Issue by jamesbuckett** [kodbasen/sloop#4]
Hello.

Can the value pair FLANNEL_BACKEND=vxlan be used in the sloop.conf in place of FLANNEL_BACKEND=udp ?

**Comment by larmog** [comment]
There is currently no way to pass other args to flannel than `FLANNEL_BACKEND`. So if your happy with the default values for `VNI, Port` and `GBP` it should work. You can always edit the key  `/coreos.com/network/config` in `etcd` using `etcdctl` manually and restart the `master`.

**Comment by jamesbuckett** [comment]
Thanks that makes sense.
