### ISSUE TITLE
On reboot the Kubernetes Master does not start 

### ISSUE THREAD

**Issue by jamesbuckett** [kodbasen/sloop#6]
Hello.

If i sudo systemctl reboot all the nodes in the cluster the master kubernetes processes do not start.

On the nodes the kube_proxy starts but nothing on the master.

Is there a start script ? Are you suppose to use the sloop-turndown.sh to stop the cluster before shutting it down ?

**Comment by larmog** [comment]
Use `sloop-worker.sh` or `sloop-master.sh` to bring up your nodes and `sloop-turndown.sh` to stop.

**Comment by jamesbuckett** [comment]
Thanks was not clear that I had to use `sloop-turndown.sh` to stop the master and nodes.
