### ISSUE TITLE
sudo kube-config enable-addon heapster

### ISSUE THREAD

**Issue by jamesbuckett** [kodbasen/sloop#7]
Hello. 
. 
I am trying to enable heapster via `sudo kube-config enable-addon heapster`
.
When i execute the command i get this error `Kubernetes is not running!`

However Kubernetes is running 

`kubectl cluster-info`

`$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
`

Is there anyway to enable heapster and helm via `sudo kube-config enable-addon`

**Comment by larmog** [comment]
Hi,
`kube-config` is part of [kubernetes-on-arm](https://github.com/luxas/kubernetes-on-arm) and does not work with `sloop`. However you can use the addon files if you copy them to the manifest dir (`/var/lib/kubelet/manifests`).

**Comment by jamesbuckett** [comment]
My bad. 

I have dual installed both sloop and kubernetes-on-arm and I thought `kube-config` was part of sloop.

Thanks for the update about the manifest directory.
